# Orb 'circleci/node@3.0.1' resolved to 'circleci/node@3.0.1'
version: 2
jobs:
  build-and-test:
    docker:
    - image: cimg/node:13.11
    steps:
    - checkout
    - run:
        command: |
          if [ ! -f "package.json" ]; then
            echo
            echo "---"
            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
            echo "---"
            echo
            echo "Current directory: $(pwd)"
            echo
            echo
            echo "List directory: "
            echo
            ls
            exit 1
          fi
        name: Checking for package.json.
        working_directory: ~/project
    - restore_cache:
        keys:
        - node-deps-v1-{{ .Branch }}-{{ checksum "~/project/yarn.lock" }}
    - run:
        command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  yarn install --frozen-lockfile\nfi\n"
        name: Installing YARN packages
        working_directory: ~/project
    - save_cache:
        key: node-deps-v1-{{ .Branch }}-{{ checksum "~/project/yarn.lock" }}
        paths:
        - ~/project/node_modules
    - run:
        name: Build and test
        command: yarn test
  publish:
    docker:
    - image: cimg/node:13.11
    steps:
    - checkout
    - run:
        command: |
          if [ ! -f "package.json" ]; then
            echo
            echo "---"
            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
            echo "---"
            echo
            echo "Current directory: $(pwd)"
            echo
            echo
            echo "List directory: "
            echo
            ls
            exit 1
          fi
        name: Checking for package.json.
        working_directory: ~/project
    - restore_cache:
        keys:
        - node-deps-v1-{{ .Branch }}-{{ checksum "~/project/yarn.lock" }}
    - run:
        command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  yarn install --frozen-lockfile\nfi\n"
        name: Installing YARN packages
        working_directory: ~/project
    - save_cache:
        key: node-deps-v1-{{ .Branch }}-{{ checksum "~/project/yarn.lock" }}
        paths:
        - ~/project/node_modules
    - run:
        name: Publish
        command: |
          yarn build
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm publish
workflows:
  CI-workflow:
    jobs:
    - build-and-test
    - hold:
        filters:
          branches:
            only: master
        type: approval
        requires:
        - build-and-test
    - publish:
        filters:
          branches:
            only: master
        requires:
        - hold
  version: 2

# Original config.yml file:
# version: 2.1
# orbs:
#   node: circleci/node@3.0.1
# jobs:
#   build-and-test:
#     executor: node/default
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: yarn
#       - run:
#           name: 'Build and test'
#           command: 'yarn test'
#   publish:
#     executor: node/default
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: yarn
#       - run:
#           name: 'Publish'
#           command: |
#             yarn build
#             echo \"//registry.npmjs.org/:_authToken=$NPM_TOKEN\" > ~/.npmrc
#             npm publish
# 
# workflows:
#   CI-workflow:
#     jobs:
#       - build-and-test
#       - hold:
#           type: approval
#           requires:
#             - build-and-test
#           filters:
#             branches:
#               only: master
#       - publish:
#           requires:
#             - hold
#           filters:
#             branches:
#               only: master