version: 2.1
orbs:
  node: circleci/node@3.0.1
  snyk: snyk/snyk@0.0.10
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - snyk/scan
      - run:
          name: 'Build and test'
          command: 'yarn test'

  publish:
    executor: node/default
    steps:
      - run:
          name: 'Publishing'
          command: |
            yarn build
            npm publish

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - publish:
          type: approval
          requires:
            - build-and-test
          filters:
            branches:
              only: master
