version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '16.15.1'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Build and test'
          command: 'yarn test'
  publish:
    executor:
      name: node/default
      tag: '16.15.1'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: 'Publish'
          command: |
            yarn build
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            npm publish

workflows:
  CI-workflow:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - build-and-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
