version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: |
            echo "registry=https://registry.npmjs.org/" > ~/.npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn install --frozen-lockfile
            yarn test
            yarn build
  test-and-publish:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: |
            echo "registry=https://registry.npmjs.org/" > ~/.npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn install --frozen-lockfile
            yarn test
            npm publish

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - test-and-publish:
          filters:
            branches:
              only: master
